/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControlReserva;
import control.ControlSala;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class Inicio extends javax.swing.JFrame {
private MessageBean bm;
    private ControlReserva cr;
    private ControlSala cs;
     DefaultTableModel model;
     DefaultTableModel model2;
    public Inicio() throws RemoteException, NotBoundException {
        
        initComponents();
     
          for (int i = 7; i < 21; i++) {
              
             jComboBox1.addItem(i+1+":00"+":00");  
             jComboBox1.addItem(i+1+":30"+":00");  
            
        }
          
          for (int i = 7; i < 21; i++) {
              
             jComboBox2.addItem(i+2+":00"+":00");  
             jComboBox2.addItem(i+2+":30"+":00");  
            
        }
          bm=new MessageBean();
        cr = new ControlReserva();
        cs = new ControlSala();
         model = (DefaultTableModel) jTable1.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 23, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/booking.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CREAR RESERVA");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel16.setText("INGRESAR FECHA DE RESERVA: ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel18.setText("INGRESAR HORA DE ENTRADA: ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel15.setText("INGRESAR HORA DE SALIDA: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel19.setText("INGRESAR ID DE LA SALA: ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel17.setText("INGRESE SU ID: ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 60, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 60, -1));

        jButton1.setText("CREAR RESERVA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 480, 380));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("LISTAR SALAS");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check-mark.png"))); // NOI18N
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_sala", "nombre_sala", "ubica_sala", "sal_num_equ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 480, 100));

        jButton2.setText("LISTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 480, 280));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("LISTAR RESERVAS");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check-mark.png"))); // NOI18N
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 40, 40));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "res_id_doc", "res_id_sal", "fecha", "hora_ini", "hora_fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 100));

        jButton3.setText("LISTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 450, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
         String fechaComoCadena = sdf.format(jDateChooser1.getDate());
         Calendar fecha = new GregorianCalendar();
         int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        
        
         java.util.Date parse;
    try {
         int numero = (int) (Math.random() * 9999) + 1;
        
        parse = sdf.parse(fechaComoCadena);
        java.sql.Date sqlDate = new java.sql.Date(parse.getTime());
     
        java.sql.Time n = java.sql.Time.valueOf((String) jComboBox1.getSelectedItem());
       
        System.out.println(año+"-"+mes+"-"+dia);
        java.sql.Time f = java.sql.Time.valueOf((String) jComboBox2.getSelectedItem());
         System.out.println("fecha fin:" +f);
        System.out.println("fecha ini:" +n);

         persistence.Res u=cr.searchReserva(Integer.parseInt(jTextField1.getText()));
         
               Calendar calendario = Calendar.getInstance();
               calendario.setTime(sqlDate);
              int an = calendario.get(Calendar.YEAR);       
              int mm = calendario.get(Calendar.MONTH);
              int ddd = calendario.get(Calendar.DAY_OF_MONTH);
              System.out.println("sql:" + an+mm+ddd);
              
              
              Calendar cal = Calendar.getInstance();
		cal.set(Calendar.YEAR,an);
                cal.set(Calendar.MONTH,mm);
                cal.set(Calendar.DAY_OF_MONTH, ddd);
		//cal.set(Calendar.HOUR_OF_DAY,17);
		//cal.set(Calendar.MINUTE,43);
		//cal.set(Calendar.SECOND,0);
		//cal.set(Calendar.MILLISECOND,0);
		Calendar cal2 = Calendar.getInstance();

		cal2.set(Calendar.YEAR,año);
                cal2.set(Calendar.MONTH,mes);
                cal2.set(Calendar.DAY_OF_MONTH,dia);
		/*cal2.set(Calendar.HOUR_OF_DAY,17);
		cal2.set(Calendar.MINUTE,42);
		cal2.set(Calendar.SECOND,0);
		cal2.set(Calendar.MILLISECOND,0);*/
		java.util.Date d2 = cal2.getTime();
		java.util.Date d = cal.getTime();	
                
                int rangohora = f.getHours()-n.getHours();
                int rangomin = f.getMinutes() - n.getMinutes();
                
                int ranghorasql = u.getRes_hora_fin().getHours() - u.getRes_hora_ini().getHours();
                int rangominsql = u.getRes_hora_fin().getMinutes() - u.getRes_hora_ini().getMinutes();
                
              
		
                if(u.getRes_id_sal()==Integer.parseInt(jTextField1.getText()) && n.getHours()>= u.getRes_hora_ini().getHours() && n.getHours() < u.getRes_hora_fin().getHours() && u.getRes_fecha().equals(sqlDate)){
                    bm.warning("La sala se encuentra reservada"+ " " +u.getRes_fecha()+ " " + u.getRes_hora_ini() + " " + u.getRes_hora_fin());
                    
                    
                }else{
                    		if(d.compareTo(d2) == 1 || d.compareTo(d2) == 0) {
                    
            if(cr.addReserva(n, f, Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()), sqlDate, numero)){
            bm.information("Se agrego con exito !");
            
            jTextField1.setText(null);
            jTextField2.setText(null);
            }  
		}
                
                else{                   
                    if(d.compareTo(d2) == -1) {
			 bm.error("Hora o fecha no disponible, verifique de nuevo !");
		}                  
                }
                }
               
                
		
             
	
  
       
    } catch (ParseException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    
    
    
    
					
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       model = (DefaultTableModel) jTable1.getModel();
        List<persistence.Sala> nn = cs.listSalas();
        for (persistence.Sala nn1 : nn) {
               
                model.insertRow(model.getRowCount(), new Object[]{nn1.getSal_id(),  nn1.getSal_nombre(),  nn1.getSal_ubicacion(),nn1.getSal_num_equ()});
                
        }
        model.setRowCount(0);
        for (persistence.Sala nn1 : nn) {
               
                model.insertRow(model.getRowCount(), new Object[]{nn1.getSal_id(), nn1.getSal_num_equ(), nn1.getSal_ubicacion(), nn1.getSal_nombre()});
     
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  model2 = (DefaultTableModel) jTable2.getModel();
        
        List<persistence.Res> nn = cr.listReserva();
        for (persistence.Res nn1 : nn) {
               
                model2.insertRow(model2.getRowCount(), new Object[]{nn1.getRes_id_doc(),  nn1.getRes_id_sal(),  nn1.getRes_fecha(),nn1.getRes_hora_ini(), nn1.getRes_hora_fin()});
                
        }
        model2.setRowCount(0);
       for (persistence.Res nn1 : nn) {
               
                model2.insertRow(model2.getRowCount(), new Object[]{nn1.getRes_id_doc(),  nn1.getRes_id_sal(),  nn1.getRes_fecha(),nn1.getRes_hora_ini(), nn1.getRes_hora_fin()});
                
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
