/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package persistence;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Sala Value Object.
  * This class is value object representing database table salas
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Sala implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int sal_id;
    private String sal_num_equ;
    private String sal_ubicacion;
    private String sal_nombre;
    private Timestamp timestamp;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Sala () {

    }

    public Sala (int sal_idIn) {

          this.sal_id = sal_idIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getSal_id() {
          return this.sal_id;
    }
    public void setSal_id(int sal_idIn) {
          this.sal_id = sal_idIn;
    }

    public String getSal_num_equ() {
          return this.sal_num_equ;
    }
    public void setSal_num_equ(String sal_num_equIn) {
          this.sal_num_equ = sal_num_equIn;
    }

    public String getSal_ubicacion() {
          return this.sal_ubicacion;
    }
    public void setSal_ubicacion(String sal_ubicacionIn) {
          this.sal_ubicacion = sal_ubicacionIn;
    }

    public String getSal_nombre() {
          return this.sal_nombre;
    }
    public void setSal_nombre(String sal_nombreIn) {
          this.sal_nombre = sal_nombreIn;
    }

    public Timestamp getTimestamp() {
          return this.timestamp;
    }
    public void setTimestamp(Timestamp timestampIn) {
          this.timestamp = timestampIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int sal_idIn,
          String sal_num_equIn,
          String sal_ubicacionIn,
          String sal_nombreIn,
          Timestamp timestampIn) {
          this.sal_id = sal_idIn;
          this.sal_num_equ = sal_num_equIn;
          this.sal_ubicacion = sal_ubicacionIn;
          this.sal_nombre = sal_nombreIn;
          this.timestamp = timestampIn;
    }


    /** 
     * hasEqualMapping-method will compare two Sala instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Sala valueObject) {

          if (valueObject.getSal_id() != this.sal_id) {
                    return(false);
          }
          if (this.sal_num_equ == null) {
                    if (valueObject.getSal_num_equ() != null)
                           return(false);
          } else if (!this.sal_num_equ.equals(valueObject.getSal_num_equ())) {
                    return(false);
          }
          if (this.sal_ubicacion == null) {
                    if (valueObject.getSal_ubicacion() != null)
                           return(false);
          } else if (!this.sal_ubicacion.equals(valueObject.getSal_ubicacion())) {
                    return(false);
          }
          if (this.sal_nombre == null) {
                    if (valueObject.getSal_nombre() != null)
                           return(false);
          } else if (!this.sal_nombre.equals(valueObject.getSal_nombre())) {
                    return(false);
          }
          if (this.timestamp == null) {
                    if (valueObject.getTimestamp() != null)
                           return(false);
          } else if (!this.timestamp.equals(valueObject.getTimestamp())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Sala, mapping to table salas\n");
        out.append("Persistent attributes: \n"); 
        out.append("sal_id = " + this.sal_id + "\n"); 
        out.append("sal_num_equ = " + this.sal_num_equ + "\n"); 
        out.append("sal_ubicacion = " + this.sal_ubicacion + "\n"); 
        out.append("sal_nombre = " + this.sal_nombre + "\n"); 
        out.append("timestamp = " + this.timestamp + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Sala cloned = new Sala();

        cloned.setSal_id(this.sal_id); 
        if (this.sal_num_equ != null)
             cloned.setSal_num_equ(new String(this.sal_num_equ)); 
        if (this.sal_ubicacion != null)
             cloned.setSal_ubicacion(new String(this.sal_ubicacion)); 
        if (this.sal_nombre != null)
             cloned.setSal_nombre(new String(this.sal_nombre)); 
        if (this.timestamp != null)
             cloned.setTimestamp((Timestamp)this.timestamp.clone()); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}